#!/bin/bash
#===============================================================================
#
#         FILE:  sphinx_build
#
#        USAGE:  sphinx_build
#
#  DESCRIPTION:  $description
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  John van Zantvoort (jvzantvoort), john@vanzantvoort.org
#      COMPANY:  JDC
#      CREATED:  25-Mar-2019
#
# Copyright (C) 2019 John van Zantvoort
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#===============================================================================
declare -r CONST_SCRIPTPATH="$(readlink -f $0)"
declare -r CONST_SCRIPTNAME="$(basename $CONST_SCRIPTPATH .sh)"
declare -r CONST_SCRIPTDIR="$(dirname $CONST_SCRIPTPATH)"
declare -r CONST_DOCTREE="/output/tmp/doctrees"
declare -r CONST_OUTPUTBASEDIR="/output"
declare -r CONST_LOGFILE="${CONST_OUTPUTBASEDIR}/logging.txt"

function logging()
{
  local priority="$1"; shift
  printf "%s [%s] %s\n" "$CONST_SCRIPTNAME" "${priority}" "$@" | \
    tee -a ${CONST_LOGFILE}
}

function logging_err()
{
  logging "err" "$@"
}

function logging_info()
{
  logging "info" "$@"
}

function script_exit()
{
  local STRING="$1"
  local RETV="${2:-0}"
  if [ "$RETV" = "0" ]
  then
    logging_info "$STRING"
  else
    logging_err "$STRING"
  fi
  exit $RETV
}

function isabs()
{
  local path=$1; shift
  echo "$path" | grep -q "^/"
  RETV=$?
  [[ "$RETV" = "0" ]] && return 0 || return 1
}

#------------------------------------------------------------------------------#
#                                    Main                                      #
#------------------------------------------------------------------------------#
logging_info "start"

SW_SRCDIR=$1; shift
SW_DSTDIR=$1; shift

[[ -z "${SW_SRCDIR}" ]] && SW_SRCDIR="sphinxdoc"
[[ -z "${SW_DSTDIR}" ]] && SW_DSTDIR="html"
isabs "${SW_DSTDIR}"    || SW_DSTDIR="${CONST_OUTPUTBASEDIR}/${SW_DSTDIR}"

sphinx-build -E \
  -b html \
  -d ${CONST_DOCTREE} \
  -N \
  -q \
  $SW_SRCDIR $SW_DSTDIR >> "${CONST_LOGFILE}" 2>&1 \
    || script_exit "sphinx-build failed"

script_exit "end"
#------------------------------------------------------------------------------#
#                                  The End                                     #
#------------------------------------------------------------------------------#
