#!/bin/bash
CONST_SCRIPTPATH="$(readlink -f "$0")"
CONST_SCRIPTNAME="$(basename "${CONST_SCRIPTPATH}" .sh)"
CONST_DOCTREE="/output/tmp/doctrees"
CONST_OUTPUTBASEDIR="/output"
CONST_LOGFILE="${CONST_OUTPUTBASEDIR}/logging.txt"

readonly CONST_SCRIPTPATH
readonly CONST_SCRIPTNAME
readonly CONST_DOCTREE
readonly CONST_OUTPUTBASEDIR
readonly CONST_LOGFILE

function logging()
{
  local priority="$1"; shift
  printf "%s [%s] %s\n" "$CONST_SCRIPTNAME" "${priority}" "$@" | \
    tee -a ${CONST_LOGFILE}
}

function logging_err()
{
  logging "err" "$@"
}

function logging_info()
{
  logging "info" "$@"
}

function script_exit()
{
  local STRING="$1"
  local RETV="${2:-0}"
  if [ "$RETV" = "0" ]
  then
    logging_info "$STRING"
  else
    logging_err "$STRING"
  fi
  exit "$RETV"
}

function isabs()
{
  local path=$1; shift
  echo "$path" | grep -q "^/"
  RETV=$?
  [[ "$RETV" = "0" ]] && return 0 || return 1
}

#------------------------------------------------------------------------------#
#                                    Main                                      #
#------------------------------------------------------------------------------#
logging_info "start"

SW_SRCDIR=$1; shift
SW_DSTDIR=$1; shift

[[ -z "${SW_SRCDIR}" ]] && SW_SRCDIR="sphinxdoc"
[[ -z "${SW_DSTDIR}" ]] && SW_DSTDIR="html"
isabs "${SW_DSTDIR}"    || SW_DSTDIR="${CONST_OUTPUTBASEDIR}/${SW_DSTDIR}"

sphinx-build -E \
  -b html \
  -d ${CONST_DOCTREE} \
  -N \
  -q \
  $SW_SRCDIR $SW_DSTDIR 2>&1 | tee -a "${CONST_LOGFILE}"
RETV=$?

[[ "$RETV" = "0" ]] || script_exit "sphinx-build failed"

script_exit "end"
#------------------------------------------------------------------------------#
#                                  The End                                     #
#------------------------------------------------------------------------------#
